filename: "sem-{{.OS}}-{{.Arch}}"
binary: sem         # please provide a binary file name if the release filename is not the final one
targetBinary: sem   # a desired target binary file name
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
replacements:      # the replacement of os, arch
  amd64: x86_64
  darwin: Darwin
