filename: "argo-{{.OS}}-{{.Arch}}"
binary: argo         # please provide a binary file name if the release filename is not the final one
targetBinary: argo   # a desired target binary file name
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: gz
