filename: "{{.Name}}-{{.VersionNum}}-{{.OS}}-{{.Arch}}.tar.gz"
postInstall:
  cmd: curl
  args:
   - "-o"
   - /etc/systemd/system/containerd.service
   - https://raw.githubusercontent.com/containerd/cri/master/contrib/systemd-units/containerd.service
