filename: "{{.Name}}-{{.VersionNum}}-{{.OS}}-{{.Arch}}.tar.gz"
binary: containerd
additionBinaries:
- containerd-shim-runc-v2
defaultConfigFiles:
- os: linux
  path: /etc/containerd/config.toml
  content: |
    [plugins]
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "kubesphere/pause:3.2"
        [plugins."io.containerd.grpc.v1.cri".registry]
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
              endpoint = ["https://registry-1.docker.io"]
        [plugins."io.containerd.grpc.v1.cri".cni]
          bin_dir = "/opt/cni/bin"
          conf_dir = "/etc/cni/net.d"
- os: linux
  path: /usr/local/lib/systemd/system/containerd.service
  content: |
    [Unit]
    Description=containerd container runtime
    Documentation=https://containerd.io
    After=network.target

    [Service]
    ExecStartPre=/sbin/modprobe overlay
    ExecStart=/usr/local/bin/containerd
    Restart=always
    RestartSec=5
    Delegate=yes
    KillMode=process
    OOMScoreAdjust=-999
    LimitNOFILE=1048576
    # Having non-zero Limit*s causes performance problems due to accounting overhead
    # in the kernel. We recommend using cgroups to do container-local accounting.
    LimitNPROC=infinity
    LimitCORE=infinity
    TasksMax=infinity

    [Install]
    WantedBy=multi-user.target
postInstalls:
- cmd: systemctl
  args:
  - daemon-reload
- cmd: systemctl
  args:
  - enable
  - --now
  - containerd
categories:
- container
