filename: "istioctl-{{.VersionNum}}-{{.OS}}-{{.Arch}}"
binary: istioctl
targetBinary: istioctl
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
replacements:      # the replacement of os, arch
  darwin: osx
  windows: win
