filename: "gh_{{.VersionNum}}_{{.OS}}_{{.Arch}}"
binary: gh
categories:
- git
formatOverrides:   # set the file extension for different platforms
  windows: zip
replacements:
  darwin: macOS
versionCmd: '--version'
