filename: "release-notes-{{.OS}}-{{.Arch}}"
binary: release-notes
targetBinary: release-notes
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
