filename: "{{.Name}}-{{.OS}}-{{.Arch}}"
binary: kube-explorer         # please provide a binary file name if the release filename is not the final one
targetBinary: kube-explorer   # a desired target binary file name
tar: false          # if this is a tar file
