filename: "{{.Name}}_{{.VersionNum}}_{{.OS}}-{{.Arch}}"
tar: true          # if this is a tar file
categories:
- security
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
replacements:      # the replacement of os, arch
  amd64: 64bit
  darwin: macOS
  linux: Linux
