filename: "{{.Name}}-{{.OS}}-{{.Arch}}"
binary: {{.Name}}-{{.OS}}-{{.Arch}}
targetBinary: argocd-autopilot
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
