filename: "protoc-{{.VersionNum}}-{{.OS}}-{{.Arch}}"
binary: protoc         # please provide a binary file name if the release filename is not the final one
targetBinary: protoc   # a desired target binary file name
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: zip
replacements:      # the replacement of os, arch
  amd64: x86_64
  darwin: osx
categories:
- grpc
