packages:
- name: kcli
  install:
    cmd: bash
    args:
    - '-c'
    - 'curl -s https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash'
- name: nvm
  install:
    cmd: bash
    args:
    - '-c'
    - 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash'
- name: cert-manager
  install:
    cmd: kubectl
    args:
    - apply
    - '-f'
    - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
- name: openebs
  install:
    cmd: kubectl
    args:
    - apply 
    - '-f'
    - 'https://openebs.github.io/charts/openebs-operator.yaml'
- name: kubevirt
  preInstall:
  - cmd:
      cmd: kubectl
      args:
      - create
      - '-f'
      - 'https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml'
  install:
    cmd: kubectl
    args:
    - create
    - '-f'
    - https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-cr.yaml
- name: kubesphere
  preInstall:
  - cmd:
      cmd: kubectl
      args:
      - apply
      - '-f'
      - 'https://github.com/kubesphere/ks-installer/releases/download/v3.3.0-rc.1/kubesphere-installer.yaml'
  install:
    cmd: kubectl
    args:
    - apply
    - '-f'
    - https://github.com/kubesphere/ks-installer/releases/download/v3.3.0-rc.1/cluster-configuration.yaml
- name: gitpod
  preInstall:
  - cmd:
      cmd: bash
      args: 
      - '-c'
      - 'curl https://kots.io/install | bash'
  install:
    cmd: kubectl
    systemCall: true
    args:
    - kots
    - install
    - gitpod
    - '-n'
    - gitpod
- name: podman
  packageManager: apt-get
  preInstall:
  - issuePrefix: 'Ubuntu 18.04'
    cmd:
      cmd: apt-get
      args: 
      - install
      - software-properties-common
      - '-y'
  - issuePrefix: 'Ubuntu 18.04'
    cmd:
      cmd: add-apt-repository
      args: 
      - ppa:projectatomic/ppa
      - '-y'
  - issuePrefix: 'Ubuntu 20.04'
    cmd:
      cmd: bash
      args:
        - '-c'
        - 'echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list'
  - issuePrefix: 'Ubuntu 20.04'
    cmd:
      cmd: bash
      args:
        - '-c'
        - 'curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add -'
- name: kubeadm
  packageManager: apt-get
  preInstall:
  - cmd:
      cmd: apt-get
      args: 
      - update
  - cmd:
      cmd: apt-get
      args: 
      - install
      - '-y'
      - apt-transport-https
      - ca-certificates
      - curl
  - cmd:
      cmd: bash
      args:
        - '-c'
        - 'curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg'
  - cmd:
      cmd: bash
      args:
        - '-c'
        - 'echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list'
  - cmd:
      cmd: apt-get
      args: 
      - update
  - cmd:
      cmd: apt-get
      args: 
      - install
      - '-y'
      - kubelet
      - kubectl
  - cmd:
      cmd: modprobe
      args: 
      - overlay
  - cmd:
      cmd: modprobe
      args: 
      - br_netfilter
  - cmd:
      cmd: ufw
      args: 
      - disable
  - cmd:
      cmd: swapoff
      args: 
      - '-a'
- cmd:
      cmd: bash
      args:
      - '-c'
      - echo "1" > /proc/sys/net/ipv4/ip_forward
- name: vim
  packageManager: brew
- name: vim
  packageManager: apk
- name: vim
  packageManager: apt-get
- name: vim
  packageManager: yum
- name: gcc
  packageManager: apt-get
- name: bash-completion
  packageManager: brew
- name: ffmpeg
  packageManager: brew
- name: asciinema
  packageManager: brew
- name: curl
  packageManager: apk
- name: wget
  packageManager: apk
- name: openvpn
  packageManager: apt-get
- name: npm
  packageManager: apt-get
- name: go
  packageManager: snap
  install:
    args:
    - '--classic'
- name: ngrok
  packageManager: snap
- name: http-server
  packageManager: npm
- name: snyk
  packageManager: npm
- name: yarn
  packageManager: npm
- name: make
  packageManager: apt-get
- name: socat
  packageManager: apt-get
