packages:
- name: podman
  packageManager: apt-get
  preInstall:
  - issuePrefix: 'Ubuntu 18.04'
    cmd:
      cmd: apt-get
      args: 
      - install
      - software-properties-common
      - '-y'
  - issuePrefix: 'Ubuntu 18.04'
    cmd:
      cmd: add-apt-repository
      args: 
      - ppa:projectatomic/ppa
      - '-y'
  - issuePrefix: 'Ubuntu 20.04'
    cmd:
      cmd: bash
      args:
        - '-c'
        - 'echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list'
  - issuePrefix: 'Ubuntu 20.04'
    cmd:
      cmd: bash
      args:
        - '-c'
        - 'curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add -'
- name: kubeadm
  packageManager: apt-get
  preInstall:
  - cmd:
      cmd: apt-get
      args: 
      - update
  - cmd:
      cmd: apt-get
      args: 
      - install
      - '-y'
      - apt-transport-https
      - ca-certificates
      - curl
  - cmd:
      cmd: bash
      args:
        - '-c'
        - 'curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg'
  - cmd:
      cmd: bash
      args:
        - '-c'
        - 'echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list'
  - cmd:
      cmd: apt-get
      args: 
      - update
  - cmd:
      cmd: apt-get
      args: 
      - install
      - '-y'
      - kubelet
      - kubectl
  - cmd:
      cmd: modprobe
      args: 
      - overlay
  - cmd:
      cmd: modprobe
      args: 
      - br_netfilter
  - cmd:
      cmd: ufw
      args: 
      - disable
  - cmd:
      cmd: swapoff
      args: 
      - '-a'
- cmd:
      cmd: bash
      args:
      - '-c'
      - echo "1" > /proc/sys/net/ipv4/ip_forward
- name: vim
  packageManager: brew
- name: bash-completion
  packageManager: brew
- name: ffmpeg
  packageManager: brew
- name: asciinema
  packageManager: brew
