filename: "{{.Name}}_{{.OS}}_{{.Arch}}"
binary: crane
targetBinary: crane
additionBinaries:
- gcrane
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
replacements:      # the replacement of os, arch
  amd64: x86_64
  linux: Linux
  darwin: Darwin
  windows: Windows
categories:
- container
