filename: "{{.Name}}-{{.Version}}.{{.OS}}-{{.Arch}}"
binary: buildctl         # please provide a binary file name if the release filename is not the final one
targetBinary: buildctl   # a desired target binary file name
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
additionBinaries:
- buildkitd
