filename: "protoc-gen-{{.Name}}-{{.Versioin}}-{{.OS}}-{{.Arch}}"
binary: protoc-gen-grpc-gateway         # please provide a binary file name if the release filename is not the final one
targetBinary: protoc-gen-grpc-gateway   # a desired target binary file name
tar: false          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
replacements:      # the replacement of os, arch
  amd64: x86_64
categories:
- grpc
