filename: "codecov-{{.OS}}"
binary: codecov         # please provide a binary file name if the release filename is not the final one
targetBinary: codecov   # a desired target binary file name
tar: false          # if this is a tar file
replacements:      # the replacement of os, arch
  darwin: macos
categories:
- test
