filename: "{{.Name}}-{{.VersionNum}}-{{.OS}}-{{.Arch}}"
name: kubeseal
binary: kubeseal         # please provide a binary file name if the release filename is not the final one
tar: true          # if this is a tar file
formatOverrides:   # set the file extension for different platforms
  windows: zip
  linux: tar.gz
categories:
- k8s
- security
