name: Backup Git repository

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  BackupGit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: backup
      uses: jenkins-zh/git-backup-actions@v0.0.6
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        TARGET_GIT: "git@gitee.com:linuxsuren/hd-home.git"

  UpdateReadme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update readme
      uses: linuxsuren/yaml-readme@v0.0.12
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        pattern: 'config/*/*.yml'
        username: linuxsuren
        org: linuxsuren
        repo: hd-home
        sortby: filename
